version: "3"
services:
    php-apache:
        build:
            context: ./server
        ports:
            - 80:80
        volumes:
            - ./site:/var/www/site:Z
        links:
            - "mariadb"
    mariadb:
        image: mariadb
        volumes:
            - ./database:/docker-entrypoint-initdb.d:ro
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: "testuser"
            MYSQL_PASSWORD: "testpwd"
