version: '3'
services:
    php-apache:
        build:
            context: ./server/php-apache
        ports:
            - 80:80
            - 9000:9000
        volumes:
            - ./site:/var/www/site:Z
